#%Validation Profile 1.0
# org: cc-dx-runtime
# contact: ccsteelarc@salesforce.com

profile: mercury

uses:
  mercury-standards: ../lib/mercury-standards.yaml

# prefixes:
#   myvocab: http://myorg.com/vocabularies/myvocab#

disabled:
  - amf-parser.WebAPI-mediaType-datatype

violation:
  - at-least-one-2xx-or-3xx-response
  - base-uri-matches-pattern
  - camelcase-method-displayname
  - camelcase-query-parameters
  - camelcase-template-parameters
  - https-required
  - require-api-description
  - no-literal-question-marks-in-property-names
  - no-literal-question-marks-in-parameters
  - no-todo-text-in-description-fields
  - only-one-base-uri
  - require-method-description
  - require-response-description
  - require-json
  - resource-name-validation
  # - unique-display-names // Disabled as it causes serious performance degradation
  - version-format
  # - upper-camelcase-datatype // Disabled as it is not working as expected

validations:
  at-least-one-2xx-or-3xx-response: mercury-standards.at-least-one-2xx-or-3xx-response
  base-uri-matches-pattern: mercury-standards.base-uri-matches-pattern
  camelcase-method-displayname: mercury-standards.camelcase-method-displayname
  camelcase-query-parameters: mercury-standards.camelcase-query-parameters
  camelcase-template-parameters: mercury-standards.camelcase-template-parameters
  https-required: mercury-standards.https-required
  require-api-description: mercury-standards.require-api-description
  no-literal-question-marks-in-property-names: mercury-standards.no-literal-question-marks-in-property-names
  no-literal-question-marks-in-parameters: mercury-standards.no-literal-question-marks-in-parameters
  no-todo-text-in-description-fields: mercury-standards.no-todo-text-in-description-fields
  only-one-base-uri: mercury-standards.only-one-base-uri
  require-method-description: mercury-standards.require-method-description
  require-response-description: mercury-standards.require-response-description
  require-json: mercury-standards.require-json
  resource-name-validation: mercury-standards.resource-name-validation
  unique-display-names: mercury-standards.unique-display-names
  version-format: mercury-standards.version-format

  #datatype rules
  upper-camelcase-datatype: mercury-standards.upper-camelcase-datatype


