#%RAML 1.0
---
title: Test Raml File
version: v1
mediaType: application/json
protocols: https
description: This is a description of the API spec
/resource:
    /{resourceId}:
        get:
            displayName: getResource
            description: Get this resource
            responses:
                200:
                    description: OK
                404:
                    description: Resource not found
        post:
            displayName: createResource
            description: Create this resource
            responses:
                201:
                    description: Created
                404:
                    description: Resource not found
        put:
            displayName: updateResource
            description: Update this resource
            responses:
                202:
                    description: Accepted
                404:
                    description: Resource not found
        patch:
            displayName: patchResource
            description: Patch this resource
            responses:
                202:
                    description: Accepted
                404:
                    description: Resource not found
        head:
            displayName: checkResource
            description: Check presene of this resource
            responses:
                200:
                    description: Ok
                404:
                    description: Resource not found
        delete:
            displayName: patchResource
            description: Patch this resource
            responses:
                202:
                    description: Accepted
                404:
                    description: Resource not found
