#%RAML 1.0
---
{{#if title}}
title: {{title}}
{{/if}}
{{#if version}}
version: {{version}}
{{/if}}
{{#if mediaType}}
mediaType: {{mediaType}}
{{/if}}
{{#if protocols}}
protocols: {{protocols}}
{{/if}}
{{#if description}}
description: {{description}}
{{/if}}
