#%RAML 1.0
title: DefectsProcessAPI
# version: 1.0

/defects/{defectID}/1.0:
  patch:
    body:
      application/json:
        type: object
        properties:
          Task:
            type: object

