/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
/* eslint-disable @typescript-eslint/no-use-before-define */
import _ from "lodash";
import { DiffPatcher } from "jsondiffpatch";
import { ramlToolLogger } from "../logger";

/**
 * Top level keys/property names in flattened JSON-LD
 */
export const JSON_LD_KEY_GRAPH = "@graph";
export const JSON_LD_KEY_CONTEXT = "@context";
export const JSON_LD_KEY_ID = "@id";

/**
 * External property, added by jsondiffpath to indicate that the node property is an array
 */
const JSON_DIFF_PATCH_ARRAY_KEY = "_t";
const JSON_DIFF_PATCH_ARRAY_VALUE = "a";

/**
 * Difference types that can be identified by jsondiffpath
 */
export enum DiffType {
  ADDED,
  REMOVED,
  MODIFIED,
  TEXT_DIFF,
  MOVED
}

/**
 * Class to hold differences of a JSON node
 */
export class NodeDiff {
  public added?: { [key: string]: any };
  public removed?: { [key: string]: any };
  constructor(public id: string) {
    this.added = {};
    this.removed = {};
  }
}

/**
 * Find differences between two flattened JSON-LD AMF graphs
 * @param left Left JSON object to compare
 * @param right Right JSON object to compare
 *
 * @returns Array of NodeDiff objects
 */
export function findJsonDiffs(left: object, right: object): Array<NodeDiff> {
  //Verify left and right objects conform to flattened AMF graph json structure
  validateJson(left, "left");
  validateJson(right, "right");

  const jsonDiff = new DiffPatcher({
    // Define an object hash function
    objectHash: function getObjectHash(obj, index) {
      return obj["@id"];
    },
    arrays: {
      // default true, detect items moved inside the array (otherwise they will be registered as remove+add)
      detectMove: true,
      // default false, the value of items moved is not included in deltas
      includeValueOnMove: true //set to true so that we can log node ids that are moved
    },
    textDiff: {
      // default 60, minimum string length (left and right sides) to use text diff algorithm: google-diff-match-patch
      minLength: 6000
    }
  });
  //add plugin to include ID of the JSON node in the diff
  jsonDiff.processor.pipes.diff.before("collectChildren", addDiffId);
  ramlToolLogger.debug(
    `Added plugin to include node ID in the diff: ${jsonDiff.processor.pipes.diff.list()}`
  );

  const diffs = jsonDiff.diff(left, right);

  return parseDiffs(diffs);
}

/**
 * Verify object to diff/compare conform to flattened AMF graph json structure
 * @param obj Json provided to diff/compare
 * @param objLoc Left/Right json in the diff
 */
function validateJson(obj: any, objLoc: "left" | "right"): void {
  let msg;
  if (obj == null || _.isEmpty(obj)) {
    msg = `Invalid ${objLoc} object`;
    logError(msg);
    return;
  }
  //Flattened AMF graph must have valid @graph or @context properties
  const graph = obj[JSON_LD_KEY_GRAPH];
  if (graph == null) {
    msg = `${_.startCase(objLoc)} json must have ${JSON_LD_KEY_GRAPH} property`;
    logError(msg);
    return;
  }
  if (!_.isArray(graph) || graph.length == 0) {
    msg = `${JSON_LD_KEY_GRAPH} property in ${objLoc} json must be an array of json nodes`;
    logError(msg);
    return;
  }
}
function logError(msg: string): never {
  if (msg == null) {
    msg = "Unknown error in json diff";
  }
  ramlToolLogger.error(msg);
  throw new Error(msg);
}
/**
 * Parse JSON differences and generate an array of typed diff objects
 * @param diffs Differences JSON
 *
 * @returns Array of NodeDiff objects
 */
function parseDiffs(diffs: object): Array<NodeDiff> {
  const typedDiffs: Array<NodeDiff> = [];
  if (diffs == null || _.isEmpty(diffs)) {
    //no changes
    ramlToolLogger.info("No differences found by the jsondiffPatch");
    return typedDiffs;
  }

  ramlToolLogger.debug("Parsing differences generated by jsondiffPatch");
  const graphDiffs = diffs[JSON_LD_KEY_GRAPH];
  if (graphDiffs != null) {
    //process graph changes
    ramlToolLogger.debug("Parsing differences in JSON-LD graph node");
    typedDiffs.push(...parseGraph(graphDiffs));
  }
  const contextDiffs = diffs[JSON_LD_KEY_CONTEXT];
  if (contextDiffs != null) {
    //process context changes
    ramlToolLogger.debug("Parsing differences in the JSON-LD context node");
    const typedContextDiff = parseNodePropDiffs(
      JSON_LD_KEY_CONTEXT,
      contextDiffs
    );
    if (typedContextDiff != null) {
      typedDiffs.push(typedContextDiff);
    }
  }
  return typedDiffs;
}

/**
 * Parse differences for each JSON node in the graph
 * @param graphDiffs Array of JSON nodes with differences
 *
 * @returns Array of NodeDiff objects
 */
function parseGraph(graphDiffs: Array<object>): Array<NodeDiff> {
  const typedDiffs: Array<NodeDiff> = [];
  Object.keys(graphDiffs).forEach(key => {
    if (key === JSON_DIFF_PATCH_ARRAY_KEY) {
      //Ignoring the property added by jsondiffpath to indicate that graph is an array
      return;
    }
    const diff = graphDiffs[key];
    let typedDiff;
    if (_.isArray(diff)) {
      //Node is added/removed/moved
      typedDiff = addNodeDiff(diff);
    } else if (_.isObject(diff)) {
      //properties in a node are added/removed/modified/moved
      typedDiff = parseNodePropDiffs(diff[JSON_LD_KEY_ID], diff);
    }
    if (typedDiff != null) {
      typedDiffs.push(typedDiff);
    }
  });
  return typedDiffs;
}

/**
 * Parse differences to the node properties
 * @param nodeId ID of the node
 * @param diff JSON node that has differences
 *
 * @returns Instance of NodeDiff for the node if there are differences
 */
function parseNodePropDiffs(nodeId: string, diff: object): NodeDiff {
  let typedDiff = new NodeDiff(nodeId);
  Object.keys(diff)
    .filter(key => key !== JSON_LD_KEY_ID) //ignore node id
    .forEach(key => {
      const value = diff[key];

      //check if the property of the node is an array
      const isArray =
        value.hasOwnProperty(JSON_DIFF_PATCH_ARRAY_KEY) &&
        value[JSON_DIFF_PATCH_ARRAY_KEY] === JSON_DIFF_PATCH_ARRAY_VALUE;

      if (isArray) {
        //Ignore property added by jsondiffpath to indicate array property
        Object.keys(value)
          .filter(arrKey => arrKey !== JSON_DIFF_PATCH_ARRAY_KEY)
          .forEach(arrKey => {
            //Since this is flattened graph array value is either a string or a object with an id referencing other object in the graph
            const arrValue = value[arrKey];
            const diffType = getDiffType(arrValue);
            ramlToolLogger.debug(
              `Adding difference of node: ${typedDiff.id}, array property: ${key}, array key: ${arrKey}, difference type: ${DiffType[diffType]}`
            );
            addNodeArrayPropertyDiffs(key, arrValue, diffType, typedDiff);
          });
      } else {
        const diffType = getDiffType(value);
        ramlToolLogger.debug(
          `Adding difference of node: ${typedDiff.id}, property: ${key}, difference type: ${DiffType[diffType]}`
        );
        addNodePropertyDiffs(key, value, diffType, typedDiff);
      }
    });
  if (_.isEmpty(typedDiff.added) && _.isEmpty(typedDiff.removed)) {
    //when there are just moves and no actual changes, ignore the typed diff
    typedDiff = undefined;
  }
  return typedDiff;
}

/**
 * Get the type of the difference from the difference array generated by jsondiffpatch
 * @param diff Difference of a node or a node property
 *
 * @return DiffType Type of the difference
 */
function getDiffType(diff: Array<any>): DiffType {
  const diffLength = diff.length;
  if (diffLength === 1) {
    return DiffType.ADDED;
  }
  if (diffLength === 2) {
    return DiffType.MODIFIED;
  }
  if (diffLength === 3 && diff[2] === 0) {
    return DiffType.REMOVED;
  }
  if (diffLength === 3 && diff[2] === 2) {
    return DiffType.TEXT_DIFF;
  }
  if (diffLength === 3 && diff[2] === 3) {
    return DiffType.MOVED;
  }
  logError(
    `Invalid difference structure found: ${JSON.stringify(diff, null, 2)}`
  );
}

/**
 * Add node differences (add or remove) to NodeDiff object
 * @param diff Node that has been added/removed
 *
 * @returns Instance of NodeDiff for the node
 */
function addNodeDiff(diff: Array<any>): NodeDiff {
  let typedDiff;
  const diffNode = diff[0];
  const id = diffNode[JSON_LD_KEY_ID];
  const diffType = getDiffType(diff);
  ramlToolLogger.debug(
    `Parsing differences of node: ${id}, difference type: ${DiffType[diffType]}`
  );
  switch (diffType) {
    case DiffType.ADDED:
      typedDiff = new NodeDiff(id);
      typedDiff.added[id] = diffNode;
      break;
    case DiffType.REMOVED:
      typedDiff = new NodeDiff(id);
      typedDiff.removed[id] = diffNode;
      break;
    case DiffType.MOVED:
      ramlToolLogger.debug(`Ignoring the move of node: ${id}`);
      break;
    default:
      /**
       *  Note: MODIFIED, TEXT_DIFF are not valid for node as diff is by node id
       */
      logError(
        `Invalid difference type for node: ${DiffType[diffType]}, node: ${id}`
      );
  }
  return typedDiff;
}

/**
 * Add node property differences to NodeDiff object
 * @param key Name of the property that has difference
 * @param diff Differences of the property
 * @param diffType Type of the difference
 * @param typedDiff Type object for the difference
 * @param isArray Flag to indicate if the property is a array
 */
function addNodePropertyDiffs(
  key: string,
  diff: Array<any>,
  diffType: DiffType,
  typedDiff: NodeDiff
): void {
  switch (diffType) {
    case DiffType.ADDED:
      typedDiff.added[key] = diff[0];
      break;
    case DiffType.MODIFIED:
      typedDiff.removed[key] = diff[0];
      typedDiff.added[key] = diff[1];
      break;
    case DiffType.REMOVED:
      typedDiff.removed[key] = diff[0];
      break;
    case DiffType.TEXT_DIFF:
      //TODO: Handle text diffs where the text length exceeds the configured length
      //parseTextDiff(diff[0);
      break;
    default:
      logError(
        `Invalid difference type for node property: ${DiffType[diffType]},  node: ${typedDiff.id}, property: ${key}`
      );
  }
}

function addNodeArrayPropertyDiffs(
  key: string,
  diff: Array<any>,
  diffType: DiffType,
  typedDiff: NodeDiff
): void {
  switch (diffType) {
    case DiffType.ADDED:
      if (typedDiff.added[key] == null) {
        typedDiff.added[key] = [];
      }
      typedDiff.added[key].push(diff[0]);
      break;
    case DiffType.REMOVED:
      if (typedDiff.removed[key] == null) {
        typedDiff.removed[key] = [];
      }
      typedDiff.removed[key].push(diff[0]);
      break;
    case DiffType.MOVED:
      ramlToolLogger.debug(
        `Ignoring the moves of node: ${typedDiff.id}, property: ${key}`
      );
      break;
    default:
      logError(
        `Invalid difference type for node array property value: ${DiffType[diffType]},  node: ${typedDiff.id}, property: ${key}`
      );
  }
}

/**
 * jsondiffpatch plugin to add node ID to the difference
 */
// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
const addDiffId = <any>function(context) {
  if (
    context.leftType === "object" &&
    typeof context.left["@id"] !== "undefined"
  ) {
    const changed = !!_.find(
      context.children,
      childContext => childContext.result
    );
    if (changed) {
      context.setResult({
        "@id": context.right["@id"]
      });
    }
  }
};
addDiffId.filterName = "addDiffId";
