#%RAML 1.0

title: Shop API
x-salesforce-sdk-name: Custom Shop API Name
x-salesforce-sdk-name: Custom Shop API Name 2 (not used)
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/27d5ffea-96a7-447b-b595-2b0e837a20c6/s/-/dw/shop/v19_5
version: v1
description: This is a base shop api for testing purposes
protocols: https
mediaType: application/json
