#%Validation Profile 1.0

profile: sdk-ready

extends: RAML

disabled:
  - amf-parser.WebAPI-mediaType-datatype

violation:
  - at-least-one-2xx-or-3xx-response
  - camelcase-method-displayname
  - https-required
  - require-api-description
  - require-method-description
  - require-response-description
  - require-json
  - resource-name-validation
  - version-format

validations:

  at-least-one-2xx-or-3xx-response:
    message: Methods must have at least one 2xx or 3xx response
    targetClass: hydra.Operation
    functionConstraint:
      code: |
        function(method) {
          const re = /[23][0-9][0-9]/;
          let returns = (method["hydra:returns"] || []);
          for (let i = 0; i < returns.length; i++) {
            if (re.test(returns[i]["hydra:statusCode"])) {
              return true;
            }
          }
          return false;
        }

  camelcase-method-displayname:
    message: The API Method must have displayName and the value must be in camelcase
    targetClass: hydra.Operation
    propertyConstraints:
      schema.name:
        minCount: 1
        pattern: ^[a-z]+([A-Z][a-z0-9]*)*$

  https-required:
    message: Protocol MUST be HTTPS
    targetClass: schema.WebAPI
    propertyConstraints:
      http.scheme:
        in: [https,HTTPS]
        minCount: 1

  require-api-description:
    message: The API Description must be set
    targetClass: schema.WebAPI
    propertyConstraints:
      schema.description:
        minCount: 1

  require-method-description:
    message: The API Method description must be set
    targetClass: hydra.Operation
    propertyConstraints:
      schema.description:
        minCount: 1

  require-response-description:
    message: The description for API responses must be set
    targetClass: http.Response
    propertyConstraints:
      schema.description:
        minCount: 1

  require-json:
    message: Require the API Spec's default mediaType to be application/json
    targetClass: schema.WebAPI
    propertyConstraints:
      http.accepts:
        in: ["application/json"]
        minCount: 1

  resource-name-validation:
    message: Resource endpoints must be lowercase (Mercury only)
    targetClass: http.EndPoint
    propertyConstraints:
      http.path:
        pattern: "(\/[a-z]([a-z0-9_-])*[a-z0-9]+$)|(\/{[a-zA-Z0-9_-]+}$)"

  version-format:
    message: The version must be formatted as v[Major], for example v2
    targetClass: schema.WebAPI
    propertyConstraints:
      schema.version:
        pattern: ^v[0-9]+$
        minCount: 1


