#%Validation Profile 1.0

profile: test

prefixes:
  myvocab: http://myorg.com/vocabularies/myvocab#
  
# extends: RAML

# disabled:
#   - amf-parser.raml-status-code

violation:
  - version-constraints

validations:

  version-constraints:
    message: Version is mandatory and must be a semantic version M.m.r?
    targetClass: schema.WebAPI
    propertyConstraints:
      schema.version:
        minCount: 1