name: tests

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  linux-unit-tests:
    strategy:
      matrix:
        node: [10, 12, 14, 16]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install oasdiff
        run: |
          # Use the official install script
          curl -fsSL https://raw.githubusercontent.com/oasdiff/oasdiff/main/install.sh | sh
          # The install script puts the binary in a local bin directory, move it to system path
          sudo mv bin/oasdiff /usr/local/bin/
          # Verify installation
          oasdiff --version
      - run: npm ci
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: npm run compile
      - run: npm run test:ci
